spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campusflow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

campusflow:
  jwt:
    secret: campusflow-local-development-secret-change-me
    expiry-seconds: 86400
